

# FILE: config.yml
# These are the settings for ExtraTag. Change whatever you like but do not remove any
# non-comment lines, as this will result in errors.

plugin-prefix: "&c&l[&5&lExtraTag&c&l] &8&l"

# Custom Setting
custom-setting: false
