main: bucketofjava.tags.TagsPlugin
version: 1.0
name: tagsPlugin
api-version: 1.15

commands:
  tags:
    description: Main command for tagsPlugin. Use /tags help for more info
permissions:
  tags.user:
    description: Allows player to use the plugin's user features
    default: true
  tags.admin:
    description: Allows player to use the plugin's admin features
    default: op